### ISSUE TITLE
OPTION NAMESPACE

### ISSUE THREAD

**Issue by benjamin-0811** [Danimineiro/SqlValidator#2]
Ich als Benutzer
möchte OPTION NAMESPACE-Befehle validieren lassen,
damit ich sichergehen kann, dass ich mit dem Befehl richtig Option-keys abürzen kann.

Wenn ein SET NAMESPACE-Befehl ungültig ist, soll ich gewarnt werden.
Wenn es doch gültig ist, soll ich ein OK bekommen.

**Comment by Danimineiro** [comment]
Schon behandelt in #6
